version: '3.8'

services:
  minecraft-afk-bot:
    build: .
    container_name: minecraft-afk-bot
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - LOGS_DIRECTORY=/app/chat_logs
    volumes:
      # Mount host directory with proper permissions
      - ./chat_logs:/app/chat_logs:rw
    networks:
      - minecraft-bot-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  minecraft-bot-network:
    driver: bridge
